# Generated by Django 4.1.4 on 2023-01-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
