# Generated by Django 4.1.4 on 2023-01-25 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Manzil', 'verbose_name_plural': 'Manzillar'},
        ),
        migrations.AlterModelOptions(
            name='neighborhood',
            options={'verbose_name': 'Mahalla', 'verbose_name_plural': 'Mahallalar'},
        ),
        migrations.AlterModelOptions(
            name='smscode',
            options={'verbose_name': "Sms ko'd", 'verbose_name_plural': "Sms ko'dlar"},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Ishchi', 'verbose_name_plural': "Ishchilar ro'yxati"},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': "Ko'cha", 'verbose_name_plural': "Ko'chalar"},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['date'], 'verbose_name': 'Kunlik ish reja', 'verbose_name_plural': 'Kunlik ish rejalar'},
        ),
        migrations.AddField(
            model_name='work',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='work_imgs/', verbose_name='Rasim'),
        ),
        migrations.AlterField(
            model_name='address',
            name='addres_name',
            field=models.CharField(max_length=200, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Ism sharifi'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=200, verbose_name='Telefon raqami +998'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.street', verbose_name="Ko'cha"),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=255, verbose_name='MFY nomi'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='population',
            field=models.BigIntegerField(verbose_name='Aholi soni'),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name="Tastiqlash ko'di"),
        ),
        migrations.AlterField(
            model_name='smscode',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Ism sharifi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='rank',
            field=models.CharField(choices=[('Врач', 'Врач'), ('Оилавий хамшира', 'Оилавий хамшира'), ('Умумий амалий хамшира', 'Умумий амалий хамшира'), ('Доя', 'Доя'), ('Болалар хамшира', 'Болалар хамшира')], max_length=255, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ishchi username'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Ko'cha nomi"),
        ),
        migrations.AlterField(
            model_name='street',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.neighborhood', verbose_name='MFY'),
        ),
        migrations.AlterField(
            model_name='street',
            name='population',
            field=models.BigIntegerField(verbose_name='Aholi soni'),
        ),
        migrations.AlterField(
            model_name='work',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.address', verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='work',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Tekshirildi?'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='work',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.staff', verbose_name='Ishchi'),
        ),
    ]
