# Generated by Django 4.1.4 on 2023-01-14 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='rank',
            field=models.CharField(choices=[('Врач', 'Врач'), ('Оилавий хамшира', 'Оилавий хамшира'), ('Умумий амалий хамшира', 'Умумий амалий хамшира'), ('Доя', 'Доя'), ('Болалар хамшира', 'Болалар хамшира')], max_length=255),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.doctor')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.neighborhood')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.street')),
            ],
        ),
    ]
