# Generated by Django 4.1.4 on 2023-01-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_staff_rank_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
