# Generated by Django 4.1.4 on 2023-01-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_alter_work_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='staff',
            field=models.ManyToManyField(to='medical.staff'),
        ),
    ]
