# Generated by Django 4.1.4 on 2023-01-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_alter_work_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['date']},
        ),
        migrations.CreateModel(
            name='ComplateWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.address')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.staff')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
