# Generated by Django 4.1.4 on 2023-01-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_alter_work_options_complatework'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComplateWork',
            new_name='WorkStatus',
        ),
    ]
