# Generated by Django 4.1.4 on 2023-01-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_rename_complatework_workstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstatus',
            name='staff',
        ),
        migrations.AddField(
            model_name='workstatus',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical.doctor'),
            preserve_default=False,
        ),
    ]
