# Generated by Django 4.1.4 on 2023-01-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_remove_workstatus_staff_workstatus_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatus',
            name='staff',
            field=models.ManyToManyField(to='medical.staff'),
        ),
        migrations.RemoveField(
            model_name='workstatus',
            name='address',
        ),
        migrations.AddField(
            model_name='workstatus',
            name='address',
            field=models.ManyToManyField(to='medical.address'),
        ),
    ]
