# Generated by Django 4.1.4 on 2023-01-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_workstatus_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstatus',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
