# Generated by Django 4.1.4 on 2023-01-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_alter_workstatus_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstatus',
            options={},
        ),
        migrations.RemoveField(
            model_name='workstatus',
            name='date',
        ),
    ]
