# Generated by Django 4.1.4 on 2023-01-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_alter_workstatus_options_remove_workstatus_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstatus',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='workstatus',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
