# Generated by Django 4.1.4 on 2023-01-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0017_alter_workstatus_options_workstatus_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstatus',
            name='address',
        ),
        migrations.AddField(
            model_name='workstatus',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical.address'),
            preserve_default=False,
        ),
    ]
