# Generated by Django 4.1.4 on 2023-01-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0018_remove_workstatus_address_workstatus_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstatus',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medical.address'),
        ),
    ]
