# Generated by Django 4.1.4 on 2023-01-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0019_alter_workstatus_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstatus',
            name='address',
        ),
        migrations.RemoveField(
            model_name='workstatus',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='workstatus',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='work',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='work',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='WorkStatus',
        ),
        migrations.AddField(
            model_name='work',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical.staff'),
            preserve_default=False,
        ),
    ]
